import Header from '../components/header/header';
import './styles/globals.scss';

export const metadata = {
	title: 'Main Page',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body>
				<Header />
				{children}
			</body>
		</html>
	);
}
